import Head from "next/head";
import Image from "next/image";
// import styles from "../../styles/Home.module.css";

import { withIronSessionSsr } from "iron-session/next";
import { sessionOptions } from "lib/session";
import { User } from "models/auth";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    return {
      props: {
        user: req.session.user ?? {},
      },
    };
  },
  sessionOptions
);

export default function Login({ user }: { user: User }) {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Login {user.isLoggedIn ? user.username : "Guest"}</h1>

        <h2>to be implemented</h2>
      </main>
    </div>
  );
}
