import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import LogIn from "../components/logIn";
import styled from "styled-components";

import { withIronSessionSsr } from "iron-session/next";
import { sessionOptions } from "lib/session";
export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    return {
      props: {
        user: req.session.user ?? {},
      },
    };
  },
  sessionOptions
);

export default function Home({ user }) {
  const Wrapper = styled.section`
    width: 30vw;
    margin-left: auto;
    margin-right: auto;
  `;


  const SpecialLink = styled.a`
    text-decoration: underline;
    cursor: pointer;
  `;

  return (
    <div className={styles.container}>
      <Head>
        <title>React Budget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <LogIn />
          <Link href="/signUp">
           <SpecialLink>Sign up now!</SpecialLink>
          </Link>
      </Wrapper>
    </div>
  );
}
