import Head from "next/head";
export default function Setting() {
  return (
    <div>
      <Head>
        <title>Budget | Setting</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Setting</h1>
    </div>
  );
}
