import Head from "next/head";

const bigCategories = [
  "miscellaneous",
  "entertainment",
  "Food & drinks",
  "Housing",
  "Income",
  "Lifezstyle",
  "Savings",
  "Transportation",
];

export default function Setting() {
  console.log(bigCategories);
  return (
    <div>
      <Head>
        <title>Budget | Setting</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Setting</h1>
    </div>
  );
}
